apiVersion: v1
kind: Service
metadata:
  name: es-http
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "9200"
    port: 9200
  selector:
    app: es01

---

apiVersion: v1
kind: Service
metadata:
  name: es01
spec:
  type: ClusterIP
  ports:
  - name: "9300"
    port: 9300
  selector:
    app: es01

---

apiVersion: v1
kind: Service
metadata:
  name: es02
spec:
  type: ClusterIP
  ports:
  - name: "9300"
    port: 9300
  selector:
    app: es02

---

apiVersion: v1
kind: Service
metadata:
  name: es03
spec:
  type: ClusterIP
  ports:
  - name: "9300"
    port: 9300
  selector:
    app: es03
